### ISSUE TITLE
[Feature Request] Roll Table on X Axis and y Axis

### ISSUE THREAD

**Issue by jethoof** [javalent/dice-roller#166] opened 2023-03-09 19:08 UTC
I mentioned this in discord and wanted to make a request on a function to roll a table that has a range on X and Y axis and return the result from both die rolls.

| axis | 1   | 2   | 3   |
| ---- | --- | --- | --- |
| 1    | 1   | 2   | 3   |
| 2    | 2   | 4   | 6   |
| 3    | 3   | 6   | 9   |

so when the system runs it rolls 2d3, one for x and one for y (or can be a different die like 1d6 and 1d20) and returns the appropriate location on the table.

Would this be a possible feature in the near future?

**Comment by valentine195** [comment] 2023-03-12 17:45
Can this be considered closed? Does it need any more work?

**Comment by jethoof** [comment] 2023-03-12 23:10
If I am greedy then I would say it's be amazing to have a range to go along with but that would be a next feature? a 2d rollable matrix makes it easier for more complex table uses. 

Thank you so much for the update!

**Comment by sigrunixia** [comment] 2023-04-21 02:16
A range to go along with it would be a duplicate of #149 . :) Closing issue.

**Closed by sigrunixia** 2023-04-21 02:16 UTC
Labels: feature
