### ISSUE TITLE
[Bug]: no rendering

### ISSUE THREAD

**Issue by bayang** [javalent/dice-roller#202] opened 2023-04-27 14:47 UTC
The bug tracker is **ONLY** used for reporting bugs.

## Version Check

Linux, obsidian installed through flatpak.
Debug info from obsidian menu : 
SYSTEM INFO:
	Obsidian version: v1.1.16
	Installer version: v1.1.16
	Operating system: #1 SMP PREEMPT Thu Apr 20 11:41:14 UTC 2023 5.15.108-1-MANJARO
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal v6.3.2
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 14
	Plugins enabled: 1
		1: Dice Roller v8.14.5

All other plugins have been disabled.

## What is the expected behavior?

Seeing dice rolls when entering commands.

## What is the current behavior?

When using `dice: ` or `dice-mod: ` command, no dice is rendered. (render dice flag is enabled in settings or using the |render individual flag)
When using `dice: ` command it is possible to trigger a renering :  type command and see roll result (no render happened) then click dice icon in the note : a render happens and a new result is displayed

Also, if "display dice button with results" is turned off in config, 

 clicking a dice in the side bar dice roller triggers an error in console, produces nothing and the roll button stays disabled.

## What are the A-to-Z Steps to Reproduce your Bug?

type command and see output. (see attachment)

see video in attachment

## Error Codes

```
app.js:1 Obsidian Developer Console
plugin:obsidian-dice-roller:5732 DiceRoller plugin loaded
plugin:obsidian-dice-roller:505 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'detach')
    at Qe.roll (plugin:obsidian-dice-roller:505:21832)
roll @ plugin:obsidian-dice-roller:505
await in roll (async)
eval @ plugin:obsidian-dice-roller:505
(anonymous) @ app.js:1

```

## Screenshots and Video

see video in attachment
[obsidian.md-1682602991960.log](https://github.com/javalent/dice-roller/files/11344804/obsidian.md-1682602991960.log)

https://user-images.githubusercontent.com/11558944/234898864-1d5036d0-0a08-453a-ab35-daec0436e54e.mp4

**Comment by bayang** [comment] 2023-04-27 15:33
I played a bit with the console in the dev tools in obsidian.
I tried this (I don't know if it is the kind of code used in inline rolls though) : 
This is one session, all lines pasted one after another : 

```
const diceRollerPlugin = app.plugins.getPlugin("obsidian-dice-roller");
const diceRoller = await diceRollerPlugin.getRoller("1d6");
const res = await diceRoller.roll();   <--- no render
const res = await diceRoller.roll();   <--- render
const res1 = await diceRoller.roll();  <--- render

```

**Comment by valentine195** [comment] 2023-04-27 23:54
Yes, the plugin intentionally does not render the first roll (otherwise opening a note with a bunch of dice rolls will go nuts). 

Using the API you can force it by `roller.roll(true)`

**Comment by sigrunixia** [comment] 2023-05-06 06:54
> Yes, the plugin intentionally does not render the first roll (otherwise opening a note with a bunch of dice rolls will go nuts).
> 
> Using the API you can force it by `roller.roll(true)`
> 
> This is actually why dice-mod did not work earlier.

@valentine195 would this be a reason the first roll of #196 is off?

**Comment by sigrunixia** [comment] 2023-05-20 19:32
Documented usage of using roller.roll(true). See <https://plugins.javalent.com/dice/javascript#roller.roll(true)>. 


As this was otherwise not a bug but intended, closing thread.

**Closed by sigrunixia** 2023-05-20 19:32 UTC
Labels: bug
